### ISSUE TITLE
Generates `2` `js` files instead of just one

### ISSUE THREAD

**Issue by kireerik** [tatethurston/astrojs-service-worker#14]
and it seems like the `workbox` one is not added for `precacheAndRoute`.

**Comment by tatethurston** [comment]
@kireerik Could you provide more context and a reproduction?

**Comment by tatethurston** [comment]
@kireerik the workbox runtime is not cached via precacheAndRoute, this is expected. If you’re interested you can learn more by reading the workbox documentation.

You can use the `inlineWorkboxRuntime` option to inline the runtime if you only want a single file to be generated: https://developer.chrome.com/docs/workbox/reference/workbox-webpack-plugin/#type-GenerateSW

**Comment by tatethurston** [comment]
This is the default behavior for workbox because it decreases the number of bytes over the network when the service worker updates. The workbox runtime only changes when updating workbox, so it generally doesn’t change between releases of your application, so the cached runtime can be reused across service worker installs. That said, if you want a single file for your service worker the configuration above will achieve that.
